### ISSUE TITLE
Batch num messages doesn't work - kafka recieve metrics one by one

### ISSUE THREAD

**Issue by shayyashar** [Telefonica/prometheus-kafka-adapter#58] opened 2021-01-25 13:23 UTC
Hi,
Im trying to take metrics from peometheus with adapter and batch messages of 100 but I see at kafka metrics one by one.
Someone who can help?
Thnx :)

**Comment by shayyashar** [comment] 2021-01-26 07:56
I meant that the producer send to kafka json that represents one metrics, and not json of jsons that represents more than one metric in one message.

{
     {
          Metric 1
     },
...
     {
          Metric 100
     }
}

**Comment by palmerabollo** [comment] 2021-01-27 15:32
Hi @shayyashar, I guess you are using `KAFKA_BATCH_NUM_MESSAGES: 100`, right?. That is the expected behavior.
Batching them means that they are sent in batches of 100 entries, but they are not grouped together in a complex/nested structure.

I mean, they are sent as

```
{Metric 1},
{Metric 2},
...
{Metric 100}
```

and not

```
[
  {Metric 1},
  {Metric 2},
  ...
  {Metric 100}
]

It makes sense because consumers don't need to be aware of wether they were sent in a batch or not.
I hope it helped. I'm closing this issue.

**Closed by palmerabollo** 2021-01-27 15:32 UTC
