### ISSUE TITLE
Unable to connect to ssl enabled kafka

### ISSUE THREAD

**Issue by yashdeeph709** [Telefonica/prometheus-kafka-adapter#57] opened 2020-12-01 11:12 UTC
Hi Team, 
I am trying to connect my prometheus-kafka-adapter with kafka running on aws with tls1.2. I configured the ssl parameters as specified in the documentation. But fails with this message. 

%6|1606820860.383|FAIL|rdkafka#producer-1| [thrd:<broker-address>]: <bootstrap-server-address>: Disconnected while requesting ApiVersion: might be caused by incorrect security.protocol configuration (connecting to a SSL listener?) or broker version is < 0.10 (see api.version.request) (after 1ms in state APIVERSION_QUERY)

I have these environtment variables.
export LOG_LEVEL=debug
export GIN_MODE=debug
export KAFKA_BROKER_LIST=<broker-list-with-port>
export KAFKA_SSL_CA_CERT_FILE=
export SERIALIZATION_FORMAT=avro-json
export KAFKA_SSL_CLIENT_KEY_PASS=<correct-password-verified>
export KAFKA_SSL_CLIENT_KEY_FILE=./kafka.client.keystore.jks
export KAFKA_SSL_CLIENT_CERT_FILE=./kafka.client.truststore.jks
export PATH=$PATH:/usr/local/go/bin
export PORT=9098
export APP_AUTH_URL=<something>
export KAFKA_TOPIC=my_topic_for_ssl_test
export KAFKA_SECURITY_PROTOCOL=ssl

**Comment by yashdeeph709** [comment] 2020-12-01 11:12
I also tried the api.version.request false

**Comment by palmerabollo** [comment] 2020-12-02 07:37
Hi @yashdeeph709, could you please try connecting to Kafka using kafka-console-producer from the same machine that fails? I'd like to know if the issue is in Kafka (eg. wrong Kafka advertised listener, see https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/). Are any other Kafka producers able to connect to your Kafka brokers?

**Comment by palmerabollo** [comment] 2021-01-19 13:31
I'm closing this issue because I'm not able to reproduce it. Please reopen it with additional info if needed.

**Closed by palmerabollo** 2021-01-19 13:31 UTC
