### ISSUE TITLE
Not able to write kafka

### ISSUE THREAD

**Issue by huangyong1991** [Telefonica/prometheus-kafka-adapter#52] opened 2020-07-24 02:41 UTC
there are no error or even exception messages in prometheus-kafka-adapter and prometheus server,but the datas are not able to write to kafka correctly, I confirm that the kafka is working fine. which part went wrong?can you give me some advice ? I past env and log  in the document below

**Comment by huangyong1991** [comment] 2020-07-24 02:42
#prometheus server prometheus.yml
# my global config
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
remote_write:
  - url: "http://10.132.35.102:8080/receive"
    remote_timeout: 30s
    queue_config:
      capacity: 100000
      max_shards: 10000
      min_shards: 100
      max_samples_per_send: 100
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 100ms

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'clickhouse_exporter'
    static_configs:
      - targets:
        - 10.132.35.20:19116

**Comment by huangyong1991** [comment] 2020-07-24 02:44
#prometheus server prometheus.yml
# my global config
global:
  scrape_interval:     60s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 60s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
remote_write:
  - url: "http://10.132.35.102:8080/receive"
    remote_timeout: 30s
    queue_config:
      capacity: 100000
      max_shards: 10000
      min_shards: 100
      max_samples_per_send: 100
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 100ms

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'clickhouse_exporter'
    static_configs:
      - targets:
        - 10.132.35.20:19116

**Comment by huangyong1991** [comment] 2020-07-24 02:50
[prometheus.docx](https://github.com/Telefonica/prometheus-kafka-adapter/files/4970016/prometheus.docx)
there are some log and configuration files

**Comment by palmerabollo** [comment] 2020-07-24 06:16
Closing as a duplicate of https://github.com/Telefonica/prometheus-kafka-adapter/issues/50

**Closed by palmerabollo** 2020-07-24 06:16 UTC
